import React from "react";
import { ContactInfo, SocialLink } from "../types";
import { PLATFORM_OPTIONS } from "../constants/socialPlatforms";

interface ContactInfoSectionProps {
  contactInfo: ContactInfo;
  onUpdate: (updatedInfo: ContactInfo) => void;
  socialLinkErrors: Record<number, string>; // Map of index to error message
  onSocialLinkChange: (index: number, field: keyof SocialLink, value: string) => void;
  onAddSocialLink: () => void;
  onRemoveSocialLink: (index: number) => void;
  autoGeneratedIndexes: Set<number>; // Track which social links have auto-generated display text
}

const ContactInfoSection: React.FC<ContactInfoSectionProps> = ({
  contactInfo,
  onUpdate,
  socialLinkErrors,
  onSocialLinkChange,
  onAddSocialLink,
  onRemoveSocialLink,
  autoGeneratedIndexes,
}) => {
  const socialLinks = contactInfo.social_links || [];

  return (
    <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-lg p-6 sm:p-8 mb-8 border border-gray-200">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-800">
          Contact Information
        </h2>
      </div>
      <p className="text-gray-600 mb-6">
        Start by filling out your basic contact information
      </p>

      {/* Responsive Grid: 1 column mobile, 2 columns tablet/desktop */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {/* Name Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Name
          </label>
          <input
            type="text"
            inputMode="text"
            autoComplete="name"
            value={contactInfo.name || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, name: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your name"
            aria-label="Full name"
          />
        </div>

        {/* Location Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Location
          </label>
          <input
            type="text"
            inputMode="text"
            autoComplete="address-level2"
            value={contactInfo.location || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, location: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your location"
            aria-label="Location"
          />
        </div>

        {/* Email Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Email
          </label>
          <input
            type="email"
            inputMode="email"
            autoComplete="email"
            value={contactInfo.email || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, email: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your email"
            aria-label="Email address"
          />
        </div>

        {/* Phone Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Phone
          </label>
          <input
            type="tel"
            inputMode="tel"
            autoComplete="tel"
            value={contactInfo.phone || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, phone: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your phone"
            aria-label="Phone number"
          />
        </div>
      </div>

      {/* Social Links Section */}
      <div className="border-t border-gray-200 pt-6">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-bold text-gray-800">Social Links</h3>
          <button
            onClick={onAddSocialLink}
            className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg transition-colors duration-200 text-sm font-semibold flex items-center gap-2"
            aria-label="Add social link"
          >
            <span>+</span>
            Add Social Link
          </button>
        </div>
        <p className="text-gray-600 mb-6 text-sm">
          Add links to your professional profiles (LinkedIn, GitHub, etc.)
        </p>

        {socialLinks.length === 0 ? (
          <div className="text-center py-8 text-gray-500 bg-gray-50 rounded-xl border-2 border-dashed border-gray-300">
            <p>No social links added yet. Click "Add Social Link" to get started.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {socialLinks.map((link, index) => (
              <div
                key={index}
                className="bg-gray-50 rounded-xl p-4 border border-gray-200 transition-all duration-200 hover:shadow-md"
              >
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {/* Platform Dropdown */}
                  <div>
                    <label className="block text-gray-700 font-semibold mb-2 text-sm">
                      Platform
                    </label>
                    <select
                      value={link.platform || ""}
                      onChange={(e) =>
                        onSocialLinkChange(index, "platform", e.target.value)
                      }
                      className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200 bg-white"
                      aria-label={`Platform for social link ${index + 1}`}
                    >
                      <option value="">Select platform...</option>
                      {PLATFORM_OPTIONS.map((option) => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* URL Field */}
                  <div>
                    <label className="block text-gray-700 font-semibold mb-2 text-sm">
                      URL
                    </label>
                    <input
                      type="url"
                      inputMode="url"
                      value={link.url || ""}
                      onChange={(e) =>
                        onSocialLinkChange(index, "url", e.target.value)
                      }
                      className={`w-full border rounded-lg p-2.5 focus:ring-2 focus:border-blue-500 transition-all duration-200 ${
                        socialLinkErrors[index]
                          ? "border-red-300 focus:ring-red-500 bg-red-50"
                          : "border-gray-300 focus:ring-blue-500"
                      }`}
                      placeholder="Enter profile URL"
                      aria-label={`URL for social link ${index + 1}`}
                      aria-invalid={socialLinkErrors[index] ? "true" : "false"}
                    />
                    {socialLinkErrors[index] && (
                      <p className="text-red-500 text-xs mt-1 flex items-center">
                        <span className="mr-1">⚠️</span>
                        {socialLinkErrors[index]}
                      </p>
                    )}
                  </div>

                  {/* Display Text Field with Magic Wand */}
                  <div>
                    <label className="block text-gray-700 font-semibold mb-2 text-sm">
                      Display Text
                    </label>
                    <div className="relative">
                      <input
                        type="text"
                        inputMode="text"
                        value={link.display_text || ""}
                        onChange={(e) =>
                          onSocialLinkChange(index, "display_text", e.target.value)
                        }
                        className="w-full border border-gray-300 rounded-lg p-2.5 pr-10 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
                        placeholder="How it appears on resume"
                        aria-label={`Display text for social link ${index + 1}`}
                      />
                      {autoGeneratedIndexes.has(index) && (
                        <span
                          className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400"
                          title="Auto-generated"
                          aria-label="Auto-generated"
                        >
                          🪄
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Remove Button */}
                <div className="mt-3 flex justify-end">
                  <button
                    onClick={() => onRemoveSocialLink(index)}
                    className="text-red-600 hover:text-red-700 hover:bg-red-50 px-3 py-1.5 rounded-lg transition-colors duration-200 text-sm font-semibold"
                    aria-label={`Remove social link ${index + 1}`}
                  >
                    Remove
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ContactInfoSection;
