import React from "react";

interface ContactInfo {
  name: string;
  location: string;
  email: string;
  phone: string;
  linkedin: string;
  linkedin_display?: string;
}

interface ContactInfoSectionProps {
  contactInfo: ContactInfo;
  onUpdate: (updatedInfo: ContactInfo) => void;
  linkedinUrlError: string;
  onLinkedInUrlChange: (url: string) => void;
  onLinkedInDisplayChange: (displayText: string) => void;
  isLinkedInTextAutoGenerated: boolean;
}

const ContactInfoSection: React.FC<ContactInfoSectionProps> = ({
  contactInfo,
  onUpdate,
  linkedinUrlError,
  onLinkedInUrlChange,
  onLinkedInDisplayChange,
  isLinkedInTextAutoGenerated,
}) => {
  return (
    <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-lg p-6 sm:p-8 mb-8 border border-gray-200">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-800">
          Contact Information
        </h2>
      </div>
      <p className="text-gray-600 mb-6">
        Start by filling out your basic contact information
      </p>

      {/* Responsive Grid: 1 column mobile, 2 columns tablet/desktop */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Name Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Name
          </label>
          <input
            type="text"
            inputMode="text"
            autoComplete="name"
            value={contactInfo.name || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, name: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your name"
            aria-label="Full name"
          />
        </div>

        {/* Location Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Location
          </label>
          <input
            type="text"
            inputMode="text"
            autoComplete="address-level2"
            value={contactInfo.location || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, location: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your location"
            aria-label="Location"
          />
        </div>

        {/* Email Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Email
          </label>
          <input
            type="email"
            inputMode="email"
            autoComplete="email"
            value={contactInfo.email || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, email: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your email"
            aria-label="Email address"
          />
        </div>

        {/* Phone Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            Phone
          </label>
          <input
            type="tel"
            inputMode="tel"
            autoComplete="tel"
            value={contactInfo.phone || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, phone: e.target.value })
            }
            className="w-full border border-gray-300 rounded-xl p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
            placeholder="Enter your phone"
            aria-label="Phone number"
          />
        </div>

        {/* LinkedIn URL Field */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            LinkedIn URL
          </label>
          <input
            type="url"
            inputMode="url"
            autoComplete="url"
            value={contactInfo.linkedin || ""}
            onChange={(e) => onLinkedInUrlChange(e.target.value)}
            className={`w-full border rounded-xl p-3 focus:ring-2 focus:border-blue-500 transition-all duration-200 ${
              linkedinUrlError
                ? "border-red-300 focus:ring-red-500 bg-red-50"
                : "border-gray-300 focus:ring-blue-500"
            }`}
            placeholder="Enter your LinkedIn URL (e.g., linkedin.com/in/yourname)"
            aria-label="LinkedIn profile URL"
            aria-invalid={linkedinUrlError ? "true" : "false"}
            aria-describedby={linkedinUrlError ? "linkedin-error" : undefined}
          />
          {linkedinUrlError && (
            <p
              id="linkedin-error"
              className="text-red-500 text-sm mt-1 flex items-center"
              role="alert"
            >
              <span className="mr-1" aria-hidden="true">⚠️</span>
              {linkedinUrlError}
            </p>
          )}
        </div>

        {/* LinkedIn Display Text Field with Magic Wand */}
        <div>
          <label className="block text-gray-700 font-semibold mb-2">
            LinkedIn Display Text
            <span className="text-gray-500 text-sm font-normal ml-2">
              (How it appears on your resume)
            </span>
          </label>
          <div className="relative">
            <input
              type="text"
              inputMode="text"
              value={contactInfo.linkedin_display || ""}
              onChange={(e) => onLinkedInDisplayChange(e.target.value)}
              className="w-full border border-gray-300 rounded-xl p-3 pr-10 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200"
              placeholder="e.g., John Doe, LinkedIn Profile, or LinkedIn"
              aria-label="LinkedIn display text for resume"
            />
            {isLinkedInTextAutoGenerated && (
              <span
                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 transition-opacity duration-200"
                title="Auto-generated suggestion"
                aria-label="Auto-generated"
              >
                🪄
              </span>
            )}
          </div>
          <p className="text-gray-500 text-xs mt-1">
            We'll suggest professional text, but you can customize it however you like
          </p>
        </div>
      </div>
    </div>
  );
};

export default ContactInfoSection;
