import React from "react";
import { Plus, Trash2, TriangleAlert, Wand2 } from "lucide-react";
import { ContactInfo, SocialLink } from "../types";
import { PLATFORM_OPTIONS } from "../constants/socialPlatforms";

interface ContactInfoSectionProps {
  contactInfo: ContactInfo;
  onUpdate: (updatedInfo: ContactInfo) => void;
  socialLinkErrors: Record<number, string>; // Map of index to error message
  onSocialLinkChange: (index: number, field: keyof SocialLink, value: string) => void;
  onAddSocialLink: () => void;
  onRemoveSocialLink: (index: number) => void;
  autoGeneratedIndexes: Set<number>; // Track which social links have auto-generated display text
}

/** Form label — interface chrome, so it stays in the 500/600 band per the
 *  Two-Weight Rule. Only the colour moves onto tokens. */
const LABEL = "block text-ink font-semibold mb-2 text-sm";

/** Text input / select — 8px control radius, Deep Signal focus ring. */
const FIELD =
  "w-full border border-gray-300 rounded-lg focus:ring-2 focus:ring-accent-text focus:border-accent transition-all duration-200";

const ContactInfoSection: React.FC<ContactInfoSectionProps> = ({
  contactInfo,
  onUpdate,
  socialLinkErrors,
  onSocialLinkChange,
  onAddSocialLink,
  onRemoveSocialLink,
  autoGeneratedIndexes,
}) => {
  const socialLinks = contactInfo.social_links || [];

  return (
    <div className="section-card">
      {/* Title role: 1.25rem / 700 / ink — the same setting SectionHeader gives
          every other section title, so the page has one type spine. */}
      <h2 className="font-display text-xl font-bold text-ink mb-2">
        Contact Information
      </h2>
      <p className="font-display text-base font-extralight text-ink/60 mb-6">
        Start by filling out your basic contact information
      </p>

      {/* Responsive Grid: 1 column mobile, 2 columns tablet/desktop */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {/* Name Field */}
        <div>
          <label className={LABEL}>Name</label>
          <input
            type="text"
            inputMode="text"
            autoComplete="name"
            value={contactInfo.name || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, name: e.target.value })
            }
            className={`${FIELD} p-3`}
            placeholder="Enter your name"
            aria-label="Full name"
          />
        </div>

        {/* Location Field */}
        <div>
          <label className={LABEL}>Location</label>
          <input
            type="text"
            inputMode="text"
            autoComplete="address-level2"
            value={contactInfo.location || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, location: e.target.value })
            }
            className={`${FIELD} p-3`}
            placeholder="Enter your location"
            aria-label="Location"
          />
        </div>

        {/* Email Field */}
        <div>
          <label className={LABEL}>Email</label>
          <input
            type="email"
            inputMode="email"
            autoComplete="email"
            value={contactInfo.email || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, email: e.target.value })
            }
            className={`${FIELD} p-3`}
            placeholder="Enter your email"
            aria-label="Email address"
          />
        </div>

        {/* Phone Field */}
        <div>
          <label className={LABEL}>Phone</label>
          <input
            type="tel"
            inputMode="tel"
            autoComplete="tel"
            value={contactInfo.phone || ""}
            onChange={(e) =>
              onUpdate({ ...contactInfo, phone: e.target.value })
            }
            className={`${FIELD} p-3`}
            placeholder="Enter your phone"
            aria-label="Phone number"
          />
        </div>
      </div>

      {/* Social Links Section */}
      <div className="border-t border-gray-200 pt-6">
        <h3 className="font-display text-base font-bold text-ink mb-2">
          Social Links
        </h3>
        <p className="font-display text-base font-extralight text-ink/60 mb-6">
          Add links to your professional profiles (LinkedIn, GitHub, etc.)
        </p>

        {socialLinks.length === 0 ? (
          /* The empty state is the add affordance. It used to be a dashed box
             telling you to go press a green button somewhere else — two
             controls for one action, and the dashed border spent on a div that
             could not be clicked. */
          <p className="font-display text-base font-extralight text-ink/60 mb-4">
            No social links added yet.
          </p>
        ) : (
          <div className="space-y-4 mb-4">
            {socialLinks.map((link, index) => (
              <div
                key={index}
                className="bg-chalk rounded-xl p-4 border border-gray-200 shadow-sm transition-shadow duration-200 hover:shadow-md"
              >
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {/* Platform Dropdown */}
                  <div>
                    <label className={LABEL}>Platform</label>
                    <select
                      value={link.platform || ""}
                      onChange={(e) =>
                        onSocialLinkChange(index, "platform", e.target.value)
                      }
                      className={`${FIELD} p-2.5 bg-white`}
                      aria-label={`Platform for social link ${index + 1}`}
                    >
                      <option value="">Select platform...</option>
                      {PLATFORM_OPTIONS.map((option) => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* URL Field */}
                  <div>
                    <label className={LABEL}>URL</label>
                    <input
                      type="url"
                      inputMode="url"
                      value={link.url || ""}
                      onChange={(e) =>
                        onSocialLinkChange(index, "url", e.target.value)
                      }
                      className={`w-full border rounded-lg p-2.5 focus:ring-2 focus:border-accent transition-all duration-200 ${
                        socialLinkErrors[index]
                          ? "border-red-300 focus:ring-red-600 bg-red-50"
                          : "border-gray-300 focus:ring-accent-text"
                      }`}
                      placeholder="Enter profile URL"
                      aria-label={`URL for social link ${index + 1}`}
                      aria-invalid={socialLinkErrors[index] ? "true" : "false"}
                    />
                    {socialLinkErrors[index] && (
                      /* red-600 (4.83:1 on white, 4.75:1 on Chalk) — red-500
                         measures 3.76:1 and fails AA at this size. */
                      <p className="text-red-600 text-xs mt-1 flex items-start gap-1">
                        <TriangleAlert
                          className="h-3.5 w-3.5 shrink-0 mt-px"
                          strokeWidth={1.75}
                          aria-hidden="true"
                        />
                        <span>{socialLinkErrors[index]}</span>
                      </p>
                    )}
                  </div>

                  {/* Display Text Field with auto-generated marker */}
                  <div>
                    <label className={LABEL}>Display Text</label>
                    <div className="relative">
                      <input
                        type="text"
                        inputMode="text"
                        value={link.display_text || ""}
                        onChange={(e) =>
                          onSocialLinkChange(index, "display_text", e.target.value)
                        }
                        className={`${FIELD} p-2.5 pr-10`}
                        placeholder="How it appears on resume"
                        aria-label={`Display text for social link ${index + 1}`}
                      />
                      {autoGeneratedIndexes.has(index) && (
                        <span
                          className="absolute right-3 top-1/2 -translate-y-1/2 text-ink/60"
                          title="Auto-generated"
                          aria-label="Auto-generated"
                        >
                          <Wand2 className="h-4 w-4" strokeWidth={1.75} />
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Remove Button */}
                <div className="mt-3 flex justify-end">
                  <button
                    type="button"
                    onClick={() => onRemoveSocialLink(index)}
                    className="btn-destructive-ghost"
                    aria-label={`Remove social link ${index + 1}`}
                    title="Remove social link"
                  >
                    <Trash2 className="h-4 w-4" strokeWidth={1.75} aria-hidden="true" />
                    Remove
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* The Ghost Add affordance — one add control, in one place, whether the
            list is empty or not. Replaces a solid Signal Green button that was
            spending the accent on a secondary action (the 10% Rule) at 36px
            tall (under the 44px floor). */}
        <button
          type="button"
          onClick={onAddSocialLink}
          className="btn-ghost-add"
          aria-label="Add social link"
        >
          <Plus className="h-4 w-4" strokeWidth={2} aria-hidden="true" />
          Add Social Link
        </button>
      </div>
    </div>
  );
};

export default ContactInfoSection;
