# Use the official Python image as a base
FROM python:3.11-slim-bullseye

# Set the working directory
WORKDIR /app

# Install wkhtmltopdf, LaTeX, and other dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    wkhtmltopdf \
    texlive-xetex \
    texlive-fonts-recommended \
    texlive-latex-recommended \
    texlive-fonts-extra \
    fontconfig \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy only the requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app
COPY . .

# Expose the port that Flask uses
EXPOSE 5000

# Command to run the Flask development server
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
