/// <reference types="vitest" />
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import ContactInfoSection from "../components/ContactInfoSection";
import { ContactInfo, SocialLink } from "../types";
import { PLATFORM_OPTIONS } from "../constants/socialPlatforms";

describe("ContactInfoSection", { timeout: 5000 }, () => {
  const mockContactInfo: ContactInfo = {
    name: "John Doe",
    location: "San Francisco, CA",
    email: "john@example.com",
    phone: "555-1234",
    social_links: [],
  };

  const mockOnUpdate = vi.fn();
  const mockOnSocialLinkChange = vi.fn();
  const mockOnAddSocialLink = vi.fn();
  const mockOnRemoveSocialLink = vi.fn();
  const mockSocialLinkErrors: Record<number, string> = {};
  const mockAutoGeneratedIndexes = new Set<number>();

  it("renders basic contact info fields", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    expect(screen.getByLabelText(/full name/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/location/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/email address/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/phone number/i)).toBeInTheDocument();
  });

  it("displays contact info values correctly", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const nameInput = screen.getByLabelText(/full name/i) as HTMLInputElement;
    const emailInput = screen.getByLabelText(/email address/i) as HTMLInputElement;
    const phoneInput = screen.getByLabelText(/phone number/i) as HTMLInputElement;
    const locationInput = screen.getByLabelText(/location/i) as HTMLInputElement;

    expect(nameInput.value).toBe("John Doe");
    expect(emailInput.value).toBe("john@example.com");
    expect(phoneInput.value).toBe("555-1234");
    expect(locationInput.value).toBe("San Francisco, CA");
  });

  it("calls onUpdate when name is changed", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const nameInput = screen.getByLabelText(/full name/i);
    fireEvent.change(nameInput, { target: { value: "Jane Smith" } });

    expect(mockOnUpdate).toHaveBeenCalledWith({
      ...mockContactInfo,
      name: "Jane Smith",
    });
  });

  it("calls onUpdate when email is changed", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const emailInput = screen.getByLabelText(/email address/i);
    fireEvent.change(emailInput, { target: { value: "jane@example.com" } });

    expect(mockOnUpdate).toHaveBeenCalledWith({
      ...mockContactInfo,
      email: "jane@example.com",
    });
  });

  it("calls onUpdate when phone is changed", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const phoneInput = screen.getByLabelText(/phone number/i);
    fireEvent.change(phoneInput, { target: { value: "555-9999" } });

    expect(mockOnUpdate).toHaveBeenCalledWith({
      ...mockContactInfo,
      phone: "555-9999",
    });
  });

  it("calls onUpdate when location is changed", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const locationInput = screen.getByLabelText(/location/i);
    fireEvent.change(locationInput, { target: { value: "New York, NY" } });

    expect(mockOnUpdate).toHaveBeenCalledWith({
      ...mockContactInfo,
      location: "New York, NY",
    });
  });

  it("displays 'Add Social Link' button", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const addButton = screen.getByRole("button", { name: /add social link/i });
    expect(addButton).toBeInTheDocument();
  });

  it("calls onAddSocialLink when 'Add Social Link' button is clicked", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const addButton = screen.getByRole("button", { name: /add social link/i });
    fireEvent.click(addButton);

    expect(mockOnAddSocialLink).toHaveBeenCalledTimes(1);
  });

  it("displays empty state when no social links exist", () => {
    render(
      <ContactInfoSection
        contactInfo={mockContactInfo}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    expect(screen.getByText(/no social links added yet/i)).toBeInTheDocument();
  });

  it("renders social links when they exist", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
        {
          platform: "github",
          url: "https://github.com/johndoe",
          display_text: "johndoe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    // Should not show empty state
    expect(screen.queryByText(/no social links added yet/i)).not.toBeInTheDocument();

    // Should show platform dropdowns
    const platformSelects = screen.getAllByLabelText(/platform for social link/i);
    expect(platformSelects).toHaveLength(2);

    // Should show URL inputs
    const urlInputs = screen.getAllByLabelText(/url for social link/i);
    expect(urlInputs).toHaveLength(2);

    // Should show display text inputs
    const displayTextInputs = screen.getAllByLabelText(/display text for social link/i);
    expect(displayTextInputs).toHaveLength(2);
  });

  it("displays correct values for existing social links", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const platformSelect = screen.getByLabelText(/platform for social link 1/i) as HTMLSelectElement;
    const urlInput = screen.getByLabelText(/url for social link 1/i) as HTMLInputElement;
    const displayTextInput = screen.getByLabelText(/display text for social link 1/i) as HTMLInputElement;

    expect(platformSelect.value).toBe("linkedin");
    expect(urlInput.value).toBe("https://linkedin.com/in/johndoe");
    expect(displayTextInput.value).toBe("John Doe");
  });

  it("calls onSocialLinkChange when platform is changed", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const platformSelect = screen.getByLabelText(/platform for social link 1/i);
    fireEvent.change(platformSelect, { target: { value: "github" } });

    expect(mockOnSocialLinkChange).toHaveBeenCalledWith(0, "platform", "github");
  });

  it("calls onSocialLinkChange when URL is changed", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const urlInput = screen.getByLabelText(/url for social link 1/i);
    fireEvent.change(urlInput, { target: { value: "https://linkedin.com/in/janedoe" } });

    expect(mockOnSocialLinkChange).toHaveBeenCalledWith(0, "url", "https://linkedin.com/in/janedoe");
  });

  it("calls onSocialLinkChange when display text is changed", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const displayTextInput = screen.getByLabelText(/display text for social link 1/i);
    fireEvent.change(displayTextInput, { target: { value: "My LinkedIn" } });

    expect(mockOnSocialLinkChange).toHaveBeenCalledWith(0, "display_text", "My LinkedIn");
  });

  it("displays remove button for each social link", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
        {
          platform: "github",
          url: "https://github.com/johndoe",
          display_text: "johndoe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const removeButtons = screen.getAllByRole("button", { name: /remove social link/i });
    expect(removeButtons).toHaveLength(2);
  });

  it("calls onRemoveSocialLink when remove button is clicked", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const removeButton = screen.getByRole("button", { name: /remove social link 1/i });
    fireEvent.click(removeButton);

    expect(mockOnRemoveSocialLink).toHaveBeenCalledWith(0);
  });

  it("displays validation error for social link URL", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "invalid-url",
          display_text: "John Doe",
        },
      ],
    };

    const errorsWithError: Record<number, string> = {
      0: "Please enter a valid LinkedIn profile URL",
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={errorsWithError}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    expect(screen.getByText(/please enter a valid linkedin profile url/i)).toBeInTheDocument();
  });

  it("applies error styling to URL input when validation fails", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "invalid-url",
          display_text: "John Doe",
        },
      ],
    };

    const errorsWithError: Record<number, string> = {
      0: "Please enter a valid LinkedIn profile URL",
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={errorsWithError}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const urlInput = screen.getByLabelText(/url for social link 1/i);
    expect(urlInput).toHaveClass("border-red-300");
    expect(urlInput).toHaveAttribute("aria-invalid", "true");
  });

  it("displays auto-generated indicator (magic wand) for auto-generated display text", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "github",
          url: "https://github.com/johndoe",
          display_text: "johndoe",
        },
      ],
    };

    const autoGenIndexes = new Set<number>([0]);

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={autoGenIndexes}
      />
    );

    const magicWand = screen.getByLabelText(/auto-generated/i);
    expect(magicWand).toBeInTheDocument();
    expect(magicWand.textContent).toBe("🪄");
  });

  it("does not display auto-generated indicator for manually entered display text", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "github",
          url: "https://github.com/johndoe",
          display_text: "My GitHub Profile",
        },
      ],
    };

    const autoGenIndexes = new Set<number>(); // Not auto-generated

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={autoGenIndexes}
      />
    );

    const magicWand = screen.queryByLabelText(/auto-generated/i);
    expect(magicWand).not.toBeInTheDocument();
  });

  it("displays all platform options in the dropdown", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "",
          url: "",
          display_text: "",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const platformSelect = screen.getByLabelText(/platform for social link 1/i);
    const options = platformSelect.querySelectorAll("option");

    // Should have 1 placeholder + all platform options
    expect(options).toHaveLength(PLATFORM_OPTIONS.length + 1);

    // Check that all platforms are present
    PLATFORM_OPTIONS.forEach((platform) => {
      expect(screen.getByRole("option", { name: platform.label })).toBeInTheDocument();
    });
  });

  it("handles multiple social links correctly", () => {
    const contactInfoWithLinks: ContactInfo = {
      ...mockContactInfo,
      social_links: [
        {
          platform: "linkedin",
          url: "https://linkedin.com/in/johndoe",
          display_text: "John Doe",
        },
        {
          platform: "github",
          url: "https://github.com/johndoe",
          display_text: "johndoe",
        },
        {
          platform: "twitter",
          url: "https://twitter.com/johndoe",
          display_text: "@johndoe",
        },
      ],
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    const platformSelects = screen.getAllByLabelText(/platform for social link/i);
    expect(platformSelects).toHaveLength(3);

    const removeButtons = screen.getAllByRole("button", { name: /remove social link/i });
    expect(removeButtons).toHaveLength(3);
  });

  it("handles contactInfo without social_links field", () => {
    const contactInfoWithoutSocialLinks: ContactInfo = {
      name: "John Doe",
      location: "San Francisco, CA",
      email: "john@example.com",
      phone: "555-1234",
      // social_links is undefined
    };

    render(
      <ContactInfoSection
        contactInfo={contactInfoWithoutSocialLinks}
        onUpdate={mockOnUpdate}
        socialLinkErrors={mockSocialLinkErrors}
        onSocialLinkChange={mockOnSocialLinkChange}
        onAddSocialLink={mockOnAddSocialLink}
        onRemoveSocialLink={mockOnRemoveSocialLink}
        autoGeneratedIndexes={mockAutoGeneratedIndexes}
      />
    );

    // Should display empty state
    expect(screen.getByText(/no social links added yet/i)).toBeInTheDocument();

    // Should still render the add button
    const addButton = screen.getByRole("button", { name: /add social link/i });
    expect(addButton).toBeInTheDocument();
  });
});
