// src/hooks/editor/useContactForm.ts
// Contact form logic hook (Layer 2) - manages contact info and social links

import { useState, useRef, useEffect, useCallback } from 'react';
import { ContactInfo, SocialLink } from '../../types';
import { UseContactFormReturn } from '../../types/editor';
import {
  validatePlatformUrl,
  generateDisplayText,
} from '../../constants/socialPlatforms';
import { validateLinkedInUrl } from '../../services/validationService';

/**
 * Props for useContactForm hook (dependency injection from Layer 1)
 */
export interface UseContactFormProps {
  contactInfo: ContactInfo | null;
  setContactInfo: (info: ContactInfo | null) => void;
}

/**
 * useContactForm Hook
 *
 * Manages contact form logic including:
 * - Contact info field updates
 * - Social link CRUD operations
 * - Social link validation with 500ms debounce
 * - Auto-generated display text from URLs
 * - Cleanup of debounce timers
 *
 * @param props - Dependency injection props from useEditorState
 * @returns Contact form operations and state
 *
 * @example
 * const contactForm = useContactForm({ contactInfo, setContactInfo });
 * contactForm.updateContactField('name', 'John Doe');
 * contactForm.handleAddSocialLink();
 */
export const useContactForm = ({
  contactInfo,
  setContactInfo,
}: UseContactFormProps): UseContactFormReturn => {
  // Social link validation errors (index -> error message)
  const [socialLinkErrors, setSocialLinkErrors] = useState<
    Record<number, string>
  >({});

  // Track which social links have auto-generated display text
  const [autoGeneratedIndexes, setAutoGeneratedIndexes] = useState<Set<number>>(
    new Set()
  );

  // Debounce timers for social link validation/auto-generation
  const socialLinkDebounceRefs = useRef<Record<number, NodeJS.Timeout>>({});

  /**
   * Cleanup all debounce timers on unmount
   */
  useEffect(() => {
    return () => {
      Object.values(socialLinkDebounceRefs.current).forEach((timer) =>
        clearTimeout(timer)
      );
      socialLinkDebounceRefs.current = {};
    };
  }, []);

  /**
   * Updates a specific ContactInfo field
   * Type-safe helper for updating contact info properties
   *
   * @param field - ContactInfo field name
   * @param value - New value for the field
   */
  const updateContactField = useCallback(
    <K extends keyof ContactInfo>(field: K, value: ContactInfo[K]) => {
      setContactInfo((prev) => {
        if (!prev) return null;
        return { ...prev, [field]: value };
      });
    },
    [setContactInfo]
  );

  /**
   * Validates LinkedIn URL
   * Re-exported from validationService for convenience
   *
   * @param url - LinkedIn URL to validate
   * @returns true if valid or empty, false if invalid
   */
  const validateLinkedIn = useCallback(
    (url: string): boolean => {
      return validateLinkedInUrl(url);
    },
    []
  );

  /**
   * Adds a new empty social link
   */
  const handleAddSocialLink = useCallback(() => {
    setContactInfo((prev) => {
      if (!prev) return null;

      const currentLinks = prev.social_links || [];
      return {
        ...prev,
        social_links: [
          ...currentLinks,
          { platform: '', url: '', display_text: '' },
        ],
      };
    });
  }, [setContactInfo]);

  /**
   * Removes a social link by index
   * Also clears associated errors, auto-generated flags, and debounce timers
   *
   * @param index - Index of social link to remove
   */
  const handleRemoveSocialLink = useCallback(
    (index: number) => {
      setContactInfo((prev) => {
        if (!prev) return null;

        const currentLinks = prev.social_links || [];
        const updatedLinks = currentLinks.filter((_, i) => i !== index);

        return {
          ...prev,
          social_links: updatedLinks,
        };
      });

      // Clear error for this index
      setSocialLinkErrors((prev) => {
        const updated = { ...prev };
        delete updated[index];
        return updated;
      });

      // Remove from auto-generated indexes
      setAutoGeneratedIndexes((prev) => {
        const updated = new Set(prev);
        updated.delete(index);
        return updated;
      });

      // Clear any pending debounce for this index
      if (socialLinkDebounceRefs.current[index]) {
        clearTimeout(socialLinkDebounceRefs.current[index]);
        delete socialLinkDebounceRefs.current[index];
      }
    },
    [setContactInfo]
  );

  /**
   * Debounced helper to generate social link display text
   * Internal function - not exposed in return type
   *
   * @param index - Social link index
   * @param platform - Platform ID
   * @param url - Profile URL
   */
  const debouncedGenerateSocialDisplayText = useCallback(
    (index: number, platform: string, url: string) => {
      // Clear existing timeout for this index
      if (socialLinkDebounceRefs.current[index]) {
        clearTimeout(socialLinkDebounceRefs.current[index]);
      }

      // Set new timeout for 500ms debounce
      socialLinkDebounceRefs.current[index] = setTimeout(() => {
        const displayText = generateDisplayText(platform, url, contactInfo?.name);

        setContactInfo((prev) => {
          if (!prev) return null;

          const currentLinks = prev.social_links || [];
          const updatedLinks = [...currentLinks];

          if (updatedLinks[index]) {
            updatedLinks[index] = {
              ...updatedLinks[index],
              display_text: displayText,
            };
          }

          return {
            ...prev,
            social_links: updatedLinks,
          };
        });

        // Mark this index as auto-generated
        setAutoGeneratedIndexes((prev) => new Set(prev).add(index));
      }, 500);
    },
    [contactInfo?.name, setContactInfo]
  );

  /**
   * Handles changes to a social link field
   * Validates URLs, auto-generates display text, manages errors
   *
   * @param index - Social link index
   * @param field - Field name (platform, url, display_text)
   * @param value - New value
   */
  const handleSocialLinkChange = useCallback(
    (index: number, field: keyof SocialLink, value: string) => {
      setContactInfo((prev) => {
        if (!prev) return null;

        const currentLinks = prev.social_links || [];
        const updatedLinks = [...currentLinks];

        if (!updatedLinks[index]) {
          updatedLinks[index] = { platform: '', url: '', display_text: '' };
        }

        updatedLinks[index] = {
          ...updatedLinks[index],
          [field]: value,
        };

        return {
          ...prev,
          social_links: updatedLinks,
        };
      });

      // Handle validation and auto-generation based on field
      if (field === 'url') {
        const link = contactInfo?.social_links?.[index];
        const platform = link?.platform || '';

        if (!value.trim()) {
          // Clear error if URL is empty
          setSocialLinkErrors((prev) => {
            const updated = { ...prev };
            delete updated[index];
            return updated;
          });

          // Clear display text if URL is empty
          setContactInfo((prev) => {
            if (!prev) return null;
            const currentLinks = prev.social_links || [];
            const updatedLinks = [...currentLinks];
            if (updatedLinks[index]) {
              updatedLinks[index] = { ...updatedLinks[index], display_text: '' };
            }
            return { ...prev, social_links: updatedLinks };
          });

          setAutoGeneratedIndexes((prev) => {
            const updated = new Set(prev);
            updated.delete(index);
            return updated;
          });
          return;
        }

        // Validate URL for the platform
        if (platform) {
          const validation = validatePlatformUrl(platform, value);

          if (!validation.valid && validation.error) {
            setSocialLinkErrors((prev) => ({
              ...prev,
              [index]: validation.error || '',
            }));
          } else {
            setSocialLinkErrors((prev) => {
              const updated = { ...prev };
              delete updated[index];
              return updated;
            });

            // Auto-generate display text if URL is valid
            debouncedGenerateSocialDisplayText(index, platform, value);
          }
        }
      } else if (field === 'platform') {
        // Re-validate URL when platform changes
        const link = contactInfo?.social_links?.[index];
        const url = link?.url || '';

        if (url && value) {
          const validation = validatePlatformUrl(value, url);

          if (!validation.valid && validation.error) {
            setSocialLinkErrors((prev) => ({
              ...prev,
              [index]: validation.error || '',
            }));
          } else {
            setSocialLinkErrors((prev) => {
              const updated = { ...prev };
              delete updated[index];
              return updated;
            });

            // Auto-generate display text for new platform
            debouncedGenerateSocialDisplayText(index, value, url);
          }
        }
      } else if (field === 'display_text') {
        // User is manually editing, remove auto-generated flag
        setAutoGeneratedIndexes((prev) => {
          const updated = new Set(prev);
          updated.delete(index);
          return updated;
        });
      }
    },
    [contactInfo, setContactInfo, debouncedGenerateSocialDisplayText]
  );

  return {
    // Contact info operations
    updateContactField,
    validateLinkedIn,

    // Social links operations
    socialLinkErrors,
    autoGeneratedIndexes,
    handleAddSocialLink,
    handleRemoveSocialLink,
    handleSocialLinkChange,
  };
};
