// src/components/editor/EditorContent.tsx
// Main content area for the Editor, including sections, drag-drop, toolbars

import React, { RefObject, useMemo } from 'react';
import { AlertCircle, X } from 'lucide-react';
import {
  DndContext,
  DragOverlay,
  DragStartEvent,
  DragEndEvent,
  SensorDescriptor,
  SensorOptions,
  CollisionDetection,
} from '@dnd-kit/core';
import {
  SortableContext,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import {
  restrictToVerticalAxis,
  restrictToWindowEdges,
} from '@dnd-kit/modifiers';

import { ContactInfo, Section, SaveStatus } from '../../types';
import { UnifiedDndContext, UnifiedDndContextValue, DraggedItemInfo } from '../../contexts/UnifiedDndContext';
import { DragLevel } from '../../hooks/editor/useUnifiedDragDrop';
import ContactInfoSection from '../ContactInfoSection';
import FormattingHelp from '../FormattingHelp';
import MobileActionBar from '../MobileActionBar';
import MobileNavigationDrawer from '../MobileNavigationDrawer';
import SectionNavigator from '../SectionNavigator';
import SectionItem from './SectionItem';

/**
 * Props for contact form functionality
 */
export interface EditorContentContactFormProps {
  socialLinkErrors: Record<number, string>;
  autoGeneratedIndexes: Set<number>;
  handleSocialLinkChange: (index: number, field: 'platform' | 'url' | 'display_text', value: string) => void;
  handleAddSocialLink: () => void;
  handleRemoveSocialLink: (index: number) => void;
}

/**
 * Props for drag and drop functionality
 */
export interface EditorContentDragDropProps {
  sensors: SensorDescriptor<SensorOptions>[];
  activeId: string | null;
  activeLevel: DragLevel | null;
  draggedSection: Section | null;
  draggedItemInfo: DraggedItemInfo | null;
  handleDragStart: (event: DragStartEvent) => void;
  handleDragEnd: (event: DragEndEvent) => void;
  handleDragCancel: () => void;
  collisionDetection: CollisionDetection;
  registerItemHandler: (sectionId: string, onReorder: (oldIndex: number, newIndex: number) => void) => void;
  unregisterItemHandler: (sectionId: string) => void;
  setDraggedItemInfo: (info: DraggedItemInfo | null) => void;
}

/**
 * Props for section management functionality
 */
export interface EditorContentSectionManagementProps {
  editingTitleIndex: number | null;
  temporaryTitle: string;
  setTemporaryTitle: React.Dispatch<React.SetStateAction<string>>;
  handleUpdateSection: (index: number, updatedSection: Section) => void;
  handleDeleteSection: (index: number) => void;
  handleDeleteEntry: (sectionIndex: number, entryIndex: number) => void;
  handleReorderEntry: (sectionIndex: number, oldIndex: number, newIndex: number) => void;
  handleTitleEdit: (index: number) => void;
  handleTitleSave: () => void;
  handleTitleCancel: () => void;
}

/**
 * Props for navigation functionality
 */
export interface EditorContentNavigationProps {
  activeSectionIndex: number;
  isSidebarCollapsed: boolean;
  scrollToSection: (sectionIndex: number) => void;
  setIsSidebarCollapsed: (collapsed: boolean) => void;
}

/**
 * Props for modal manager (subset needed by EditorContent)
 */
export interface EditorContentModalProps {
  showAIWarning: boolean;
  showAdvancedMenu: boolean;
  showNavigationDrawer: boolean;
  closeAIWarning: () => void;
  openAdvancedMenu: () => void;
  closeAdvancedMenu: () => void;
  openNavigationDrawer: () => void;
  closeNavigationDrawer: () => void;
  openSectionTypeModal: () => void;
  openHelpModal: () => void;
}

/**
 * Props for file operations (subset needed by EditorContent)
 */
export interface EditorContentFileOperationsProps {
  handleExportYAML: () => Promise<void>;
  handleFileInputChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
  fileInputRef: RefObject<HTMLInputElement>;
  loadingSave: boolean;
  loadingLoad: boolean;
}

/**
 * Props for editor actions (subset needed by EditorContent)
 */
export interface EditorContentEditorActionsProps {
  handleGenerateResume: () => Promise<void>;
  handleOpenPreview: () => Promise<void>;
  handleStartFresh: () => void;
  isDownloading: boolean;
  isOpeningPreview: boolean;
}

/**
 * Props for preview state
 */
export interface EditorContentPreviewProps {
  isGenerating: boolean;
  isStale: boolean;
}

/**
 * Props for save status
 */
export interface EditorContentSaveStatusProps {
  saveStatus: SaveStatus;
  lastSaved: Date | null;
}

/**
 * Icon registry interface (subset of useIconRegistry return)
 */
export interface EditorContentIconRegistry {
  registerIcon: (file: File) => string;
  registerIconWithFilename: (file: File, filename: string) => void;
  getIconFile: (filename: string) => File | null;
  removeIcon: (filename: string) => void;
  clearRegistry: () => void;
  getRegisteredFilenames: () => string[];
  getRegistrySize: () => number;
}

/**
 * Ref objects for scroll handling
 */
export interface EditorContentRefs {
  contactInfoRef: RefObject<HTMLDivElement>;
  sectionRefs: React.MutableRefObject<(HTMLDivElement | null)[]>;
  newSectionRef: React.MutableRefObject<HTMLDivElement | null>;
}

/**
 * Main props for EditorContent component
 */
export interface EditorContentProps {
  // Core data
  contactInfo: ContactInfo | null;
  setContactInfo: React.Dispatch<React.SetStateAction<ContactInfo | null>>;
  sections: Section[];
  supportsIcons: boolean;
  iconRegistry: EditorContentIconRegistry;

  // Auth state
  isAnonymous: boolean;
  isAuthenticated: boolean;

  // Grouped props
  contactForm: EditorContentContactFormProps;
  dragDrop: EditorContentDragDropProps;
  sectionManagement: EditorContentSectionManagementProps;
  navigation: EditorContentNavigationProps;
  modals: EditorContentModalProps;
  fileOperations: EditorContentFileOperationsProps;
  editorActions: EditorContentEditorActionsProps;
  preview: EditorContentPreviewProps;
  saveStatus: EditorContentSaveStatusProps;
  refs: EditorContentRefs;
}

/**
 * EditorContent Component
 *
 * Main content area for the Editor, including:
 * - AI Warning banner
 * - Contact Information Section
 * - Formatting Help
 * - Drag-and-drop sections with DndContext
 * - Section rendering loop (Experience, Education, IconList, Generic)
 * - DragOverlay for drag preview
 * - Mobile Action Bar
 * - Mobile Navigation Drawer
 * - Desktop Section Navigator Sidebar
 * - Hidden file input
 *
 * @example
 * <EditorContent
 *   contactInfo={contactInfo}
 *   setContactInfo={setContactInfo}
 *   sections={sections}
 *   supportsIcons={supportsIcons}
 *   iconRegistry={iconRegistry}
 *   contactForm={contactForm}
 *   dragDrop={dragDrop}
 *   sectionManagement={sectionManagement}
 *   navigation={navigation}
 *   modals={modals}
 *   fileOperations={fileOperations}
 *   editorActions={editorActions}
 *   preview={preview}
 *   saveStatus={saveStatus}
 *   refs={refs}
 * />
 */
export const EditorContent: React.FC<EditorContentProps> = ({
  contactInfo,
  setContactInfo,
  sections,
  supportsIcons,
  iconRegistry,
  isAnonymous,
  isAuthenticated,
  contactForm,
  dragDrop,
  sectionManagement,
  navigation,
  modals,
  fileOperations,
  editorActions,
  preview,
  saveStatus,
  refs,
}) => {
  // Lifted drag preview styling - scale and rotation for tactile "picked up" feel
  const liftedPreviewClasses = 'transform scale-[1.02] rotate-1';

  // Handler for adding new section
  const handleAddNewSectionClick = () => {
    modals.openSectionTypeModal();
  };

  // Memoize the unified DnD context value
  const unifiedDndContextValue: UnifiedDndContextValue = useMemo(() => ({
    registerItemHandler: dragDrop.registerItemHandler,
    unregisterItemHandler: dragDrop.unregisterItemHandler,
    setDraggedItemInfo: dragDrop.setDraggedItemInfo,
    draggedItemInfo: dragDrop.draggedItemInfo,
  }), [dragDrop.registerItemHandler, dragDrop.unregisterItemHandler, dragDrop.setDraggedItemInfo, dragDrop.draggedItemInfo]);

  return (
    <div
      className={`mx-auto px-4 sm:px-6 lg:px-8 pt-6 pb-[calc(var(--mobile-action-bar-height)+1rem)] lg:pb-[1rem] max-w-4xl lg:max-w-none transition-all duration-300 ${
        navigation.isSidebarCollapsed ? 'lg:mr-[88px]' : 'lg:mr-[296px]'
      }`}
    >
      {/* Imported Resume Review Banner */}
      {modals.showAIWarning && (
        <div className="mb-4 p-4 rounded-lg border-2 bg-blue-50 border-blue-200 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5 text-blue-600" />
          <div className="flex-1">
            <h3 className="font-semibold text-sm text-blue-900">
              Imported Resume - Please Review
            </h3>
            <p className="text-xs mt-1 text-blue-700">
              Please review all information for accuracy and completeness.
            </p>
          </div>
          <button
            onClick={modals.closeAIWarning}
            className="text-gray-400 hover:text-gray-600"
            aria-label="Close review banner"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Contact Information Section */}
      {contactInfo && (
        <div ref={refs.contactInfoRef}>
          <ContactInfoSection
            contactInfo={contactInfo}
            onUpdate={setContactInfo}
            socialLinkErrors={contactForm.socialLinkErrors}
            onSocialLinkChange={contactForm.handleSocialLinkChange}
            onAddSocialLink={contactForm.handleAddSocialLink}
            onRemoveSocialLink={contactForm.handleRemoveSocialLink}
            autoGeneratedIndexes={contactForm.autoGeneratedIndexes}
          />
        </div>
      )}

      {/* Global Formatting Help */}
      <FormattingHelp />

      {/* Resume Sections with Drag and Drop */}
      <UnifiedDndContext.Provider value={unifiedDndContextValue}>
        <DndContext
          sensors={dragDrop.sensors}
          collisionDetection={dragDrop.collisionDetection}
          onDragStart={dragDrop.handleDragStart}
          onDragEnd={dragDrop.handleDragEnd}
          onDragCancel={dragDrop.handleDragCancel}
          modifiers={[restrictToVerticalAxis, restrictToWindowEdges]}
        >
        <SortableContext
          items={sections.map((_, index) => `section-${index}`)}
          strategy={verticalListSortingStrategy}
        >
          {sections.map((section, index) => (
            <SectionItem
              key={`section-${index}`}
              index={index}
              section={section}
              sectionManagement={sectionManagement}
              refs={refs}
              supportsIcons={supportsIcons}
              iconRegistry={iconRegistry}
              isLast={index === sections.length - 1}
            />
          ))}
        </SortableContext>

        <DragOverlay modifiers={[restrictToVerticalAxis]} dropAnimation={{
          duration: 250,
          easing: 'cubic-bezier(0.18, 0.67, 0.6, 1.22)',
        }}>
          {dragDrop.activeId ? (
            dragDrop.activeLevel === 'section' && dragDrop.draggedSection ? (
              // Section drag preview - lifted appearance with scale and rotation
              <div className={`bg-white backdrop-blur-sm rounded-xl shadow-2xl border-2 border-blue-400 px-6 py-4 max-w-md cursor-grabbing ${liftedPreviewClasses}`}>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center">
                    <div className="flex flex-col gap-0.5">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                    </div>
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-800 truncate">
                      {dragDrop.draggedSection.name}
                    </h3>
                    <p className="text-sm text-gray-500 capitalize">
                      {dragDrop.draggedSection.type?.replace(/-/g, ' ') || 'Section'}
                    </p>
                  </div>
                </div>
              </div>
            ) : dragDrop.activeLevel === 'item' && dragDrop.draggedItemInfo ? (
              // Item drag preview with actual content - lifted appearance
              <div className={`bg-white backdrop-blur-sm rounded-lg shadow-2xl border-2 border-blue-400 px-4 py-3 max-w-sm cursor-grabbing ${liftedPreviewClasses}`}>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center flex-shrink-0">
                    {dragDrop.draggedItemInfo.type === 'experience' ? (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    ) : dragDrop.draggedItemInfo.type === 'education' ? (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path d="M12 14l9-5-9-5-9 5 9 5z" />
                        <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
                      </svg>
                    ) : dragDrop.draggedItemInfo.type === 'certification' ? (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
                      </svg>
                    ) : (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                      </svg>
                    )}
                  </div>
                  <div className="min-w-0 flex-1">
                    <h4 className="font-semibold text-gray-800 text-sm truncate">
                      {dragDrop.draggedItemInfo.label || 'Untitled'}
                    </h4>
                    {dragDrop.draggedItemInfo.sublabel && (
                      <p className="text-xs text-gray-500 truncate">{dragDrop.draggedItemInfo.sublabel}</p>
                    )}
                  </div>
                </div>
              </div>
            ) : dragDrop.activeLevel === 'item' ? (
              // Fallback item preview - lifted appearance
              <div className={`bg-white backdrop-blur-sm rounded-lg shadow-2xl border-2 border-blue-400 px-4 py-3 max-w-sm cursor-grabbing ${liftedPreviewClasses}`}>
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-md bg-blue-100 flex items-center justify-center">
                    <svg className="w-4 h-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                  </div>
                  <span className="text-sm text-gray-700 font-medium">Moving item</span>
                </div>
              </div>
            ) : dragDrop.activeLevel === 'subitem' && dragDrop.draggedItemInfo ? (
              // Subitem drag preview with actual content - lifted appearance
              <div className={`bg-white backdrop-blur-sm rounded-md shadow-xl border-2 border-blue-400 px-3 py-2.5 max-w-md cursor-grabbing ${liftedPreviewClasses}`}>
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded bg-blue-100 flex items-center justify-center flex-shrink-0">
                    <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                  </div>
                  <span className="text-sm text-gray-700 truncate">{dragDrop.draggedItemInfo.label}</span>
                </div>
              </div>
            ) : dragDrop.activeLevel === 'subitem' ? (
              // Fallback subitem preview - lifted appearance
              <div className={`bg-white backdrop-blur-sm rounded-md shadow-xl border-2 border-blue-400 px-3 py-2 max-w-xs cursor-grabbing ${liftedPreviewClasses}`}>
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded bg-blue-100 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                  </div>
                  <span className="text-sm text-gray-700 font-medium">Moving bullet point</span>
                </div>
              </div>
            ) : null
          ) : null}
        </DragOverlay>
        </DndContext>
      </UnifiedDndContext.Provider>

      {/* Mobile Action Bar */}
      <MobileActionBar
        onNavigationClick={modals.openNavigationDrawer}
        onPreviewClick={editorActions.handleOpenPreview}
        onDownloadClick={editorActions.handleGenerateResume}
        isSaving={saveStatus.saveStatus === 'saving'}
        isGenerating={editorActions.isDownloading}
        isOpeningPreview={editorActions.isOpeningPreview}
        isGeneratingPreview={preview.isGenerating}
        previewIsStale={preview.isStale}
        lastSaved={saveStatus.lastSaved}
        saveError={saveStatus.saveStatus === 'error'}
        isAuthenticated={isAuthenticated}
      />

      {/* Mobile Navigation Drawer */}
      <MobileNavigationDrawer
        isOpen={modals.showNavigationDrawer}
        onClose={modals.closeNavigationDrawer}
        sections={sections}
        onSectionClick={navigation.scrollToSection}
        activeSectionIndex={navigation.activeSectionIndex}
        onAddSection={handleAddNewSectionClick}
        onExportYAML={fileOperations.handleExportYAML}
        onImportYAML={() => fileOperations.fileInputRef.current?.click()}
        onStartFresh={editorActions.handleStartFresh}
        onHelp={modals.openHelpModal}
        loadingSave={fileOperations.loadingSave}
        loadingLoad={fileOperations.loadingLoad}
      />

      {/* Desktop Section Navigator Sidebar */}
      <SectionNavigator
        sections={sections}
        onSectionClick={navigation.scrollToSection}
        activeSectionIndex={navigation.activeSectionIndex}
        onAddSection={handleAddNewSectionClick}
        onDownloadResume={editorActions.handleGenerateResume}
        onPreviewResume={editorActions.handleOpenPreview}
        onExportYAML={fileOperations.handleExportYAML}
        onImportYAML={() => fileOperations.fileInputRef.current?.click()}
        onStartFresh={editorActions.handleStartFresh}
        onHelp={modals.openHelpModal}
        isGenerating={editorActions.isDownloading}
        isOpeningPreview={editorActions.isOpeningPreview}
        isGeneratingPreview={preview.isGenerating}
        previewIsStale={preview.isStale}
        loadingSave={fileOperations.loadingSave}
        loadingLoad={fileOperations.loadingLoad}
        onCollapseChange={navigation.setIsSidebarCollapsed}
        isAnonymous={isAnonymous}
        isAuthenticated={isAuthenticated}
      />

      {/* Hidden file input */}
      <input
        ref={fileOperations.fileInputRef}
        type="file"
        accept=".yaml,.yml"
        className="hidden"
        onChange={fileOperations.handleFileInputChange}
      />
    </div>
  );
};
