// src/types/editor.ts
// Editor-specific type definitions

import { ContactInfo, Section, SocialLink } from './types';
import { DragEndEvent, DragStartEvent, SensorDescriptor } from '@dnd-kit/core';

// --- Editor State Types ---

/**
 * Target for delete confirmation dialog
 */
export interface DeleteTarget {
  type: 'section' | 'entry';
  sectionIndex: number;
  entryIndex?: number;
  sectionName?: string;
}

// --- Hook Return Type Interfaces ---

/**
 * useModalManager hook return type
 * Manages all modal/dialog states in the editor
 */
export interface UseModalManagerReturn {
  // Section type modal
  showSectionTypeModal: boolean;
  openSectionTypeModal: () => void;
  closeSectionTypeModal: () => void;

  // Delete confirmation modal
  showDeleteConfirm: boolean;
  deleteTarget: DeleteTarget | null;
  setDeleteTarget: (target: DeleteTarget | null) => void;
  openDeleteConfirm: (target: DeleteTarget) => void;
  closeDeleteConfirm: () => void;

  // Start fresh confirmation
  showStartFreshConfirm: boolean;
  openStartFreshConfirm: () => void;
  closeStartFreshConfirm: () => void;

  // Import YAML confirmation
  showImportConfirm: boolean;
  pendingImportFile: File | null;
  setPendingImportFile: (file: File | null) => void;
  openImportConfirm: (file: File) => void;
  closeImportConfirm: () => void;

  // Navigation drawer (mobile)
  showNavigationDrawer: boolean;
  openNavigationDrawer: () => void;
  closeNavigationDrawer: () => void;

  // Preview modal
  showPreviewModal: boolean;
  openPreviewModal: () => void;
  closePreviewModal: () => void;

  // Help modal
  showHelpModal: boolean;
  openHelpModal: () => void;
  closeHelpModal: () => void;

  // Auth modal
  showAuthModal: boolean;
  openAuthModal: () => void;
  closeAuthModal: () => void;

  // Download celebration modal
  showDownloadCelebration: boolean;
  openDownloadCelebration: () => void;
  closeDownloadCelebration: () => void;
}

/**
 * useEditorState hook return type
 * Core state management for resume data
 */
export interface UseEditorStateReturn {
  contactInfo: ContactInfo | null;
  setContactInfo: (info: ContactInfo | null) => void;
  sections: Section[];
  setSections: (sections: Section[]) => void;
  updateSection: (index: number, section: Section) => void;
  templateId: string | null;
  setTemplateId: (id: string | null) => void;
  supportsIcons: boolean;
  setSupportsIcons: (supports: boolean) => void;
  originalTemplateData: { contactInfo: ContactInfo; sections: Section[] } | null;
  setOriginalTemplateData: (data: { contactInfo: ContactInfo; sections: Section[] } | null) => void;
  loading: boolean;
  setLoading: (loading: boolean) => void;
  loadingError: string | null;
  setLoadingError: (error: string | null) => void;
}

/**
 * useContactForm hook return type
 * Manages contact info and social links (merged from useContactInfo + useSocialLinks)
 */
export interface UseContactFormReturn {
  // Contact info operations
  updateContactField: <K extends keyof ContactInfo>(
    field: K,
    value: ContactInfo[K]
  ) => void;
  validateLinkedIn: (url: string) => boolean;

  // Social links operations
  socialLinkErrors: Record<number, string>;
  autoGeneratedIndexes: Set<number>;
  handleAddSocialLink: () => void;
  handleRemoveSocialLink: (index: number) => void;
  handleSocialLinkChange: (
    index: number,
    field: keyof SocialLink,
    value: string
  ) => void;
}

/**
 * useSectionDragDrop hook return type
 * Handles section-level drag and drop
 */
export interface UseSectionDragDropReturn {
  activeId: string | null;
  draggedSection: Section | null;
  sensors: ReturnType<typeof useSensors>; // @dnd-kit sensors
  handleDragStart: (event: DragStartEvent) => void;
  handleDragEnd: (event: DragEndEvent) => void;
  handleDragCancel: () => void;
}

/**
 * useSectionNavigation hook return type
 * Manages sidebar and section navigation
 */
export interface UseSectionNavigationReturn {
  activeSectionIndex: number;
  setActiveSectionIndex: (index: number) => void;
  isSidebarCollapsed: boolean;
  setIsSidebarCollapsed: (collapsed: boolean) => void;
  scrollToSection: (sectionIndex: number) => void;
}

/**
 * useResumeLoader hook return type
 * Handles loading resumes from cloud/templates
 */
export interface UseResumeLoaderReturn {
  isLoadingFromUrl: boolean;
  hasLoadedFromUrl: boolean;
  cloudResumeId: string | null;
  setCloudResumeId: (id: string | null) => void;
  loadResumeFromCloud: (resumeId: string) => Promise<void>;
  loadTemplate: (templateId: string) => Promise<void>;
}

/**
 * useTourFlow hook return type
 * Manages welcome tour and idle state
 */
export interface UseTourFlowReturn {
  showWelcomeTour: boolean;
  setShowWelcomeTour: (show: boolean) => void;
  handleTourComplete: () => Promise<void>;
  showIdleTooltip: boolean;
  dismissIdleTooltip: () => void;
  isSigningInFromTour: boolean;
  handleSignInFromTour: () => void;
  handleSignInSuccess: () => void;
}

/**
 * useSectionManagement hook return type
 * Handles section CRUD operations
 */
export interface UseSectionManagementReturn {
  handleAddSection: (type: string) => Promise<void>;
  handleUpdateSection: (index: number, updatedSection: Section) => void;
  handleDeleteSection: (index: number) => void;
  handleDeleteEntry: (sectionIndex: number, entryIndex: number) => void;
  confirmDelete: () => void;
  loadingAddSection: boolean;
}

/**
 * useFileOperations hook return type
 * Handles file import/export operations
 */
export interface UseFileOperationsReturn {
  handleImportYAML: (file: File) => Promise<void>;
  handleExportYAML: () => Promise<void>;
  loadingSave: boolean;
  setLoadingSave: (loading: boolean) => void;
}

/**
 * useEditorActions hook return type
 * Top-level editor actions (download, preview, start fresh)
 */
export interface UseEditorActionsReturn {
  isDownloading: boolean;
  handleGenerateResume: () => Promise<void>;
  handlePreviewResume: () => Promise<void>;
  handleStartFresh: () => Promise<void>;
  confirmStartFresh: () => void;
}
